// Code generated by counterfeiter. DO NOT EDIT.
package cloudfoundryfakes

import (
	"net/url"
	"sync"

	"github.com/cloudfoundry-community/go-cfclient"
	"github.com/pivotalservices/ignition/cloudfoundry"
)

type FakeAPI struct {
	CreateOrgStub        func(req cfclient.OrgRequest) (cfclient.Org, error)
	createOrgMutex       sync.RWMutex
	createOrgArgsForCall []struct {
		req cfclient.OrgRequest
	}
	createOrgReturns struct {
		result1 cfclient.Org
		result2 error
	}
	createOrgReturnsOnCall map[int]struct {
		result1 cfclient.Org
		result2 error
	}
	UpdateOrgStub        func(orgGUID string, orgRequest cfclient.OrgRequest) (cfclient.Org, error)
	updateOrgMutex       sync.RWMutex
	updateOrgArgsForCall []struct {
		orgGUID    string
		orgRequest cfclient.OrgRequest
	}
	updateOrgReturns struct {
		result1 cfclient.Org
		result2 error
	}
	updateOrgReturnsOnCall map[int]struct {
		result1 cfclient.Org
		result2 error
	}
	AddIsolationSegmentToOrgStub        func(isolationSegmentGUID, orgGUID string) error
	addIsolationSegmentToOrgMutex       sync.RWMutex
	addIsolationSegmentToOrgArgsForCall []struct {
		isolationSegmentGUID string
		orgGUID              string
	}
	addIsolationSegmentToOrgReturns struct {
		result1 error
	}
	addIsolationSegmentToOrgReturnsOnCall map[int]struct {
		result1 error
	}
	ListOrgsByQueryStub        func(query url.Values) ([]cfclient.Org, error)
	listOrgsByQueryMutex       sync.RWMutex
	listOrgsByQueryArgsForCall []struct {
		query url.Values
	}
	listOrgsByQueryReturns struct {
		result1 []cfclient.Org
		result2 error
	}
	listOrgsByQueryReturnsOnCall map[int]struct {
		result1 []cfclient.Org
		result2 error
	}
	CreateSpaceStub        func(req cfclient.SpaceRequest) (cfclient.Space, error)
	createSpaceMutex       sync.RWMutex
	createSpaceArgsForCall []struct {
		req cfclient.SpaceRequest
	}
	createSpaceReturns struct {
		result1 cfclient.Space
		result2 error
	}
	createSpaceReturnsOnCall map[int]struct {
		result1 cfclient.Space
		result2 error
	}
	AssociateOrgUserStub        func(orgGUID, userGUID string) (cfclient.Org, error)
	associateOrgUserMutex       sync.RWMutex
	associateOrgUserArgsForCall []struct {
		orgGUID  string
		userGUID string
	}
	associateOrgUserReturns struct {
		result1 cfclient.Org
		result2 error
	}
	associateOrgUserReturnsOnCall map[int]struct {
		result1 cfclient.Org
		result2 error
	}
	AssociateOrgAuditorStub        func(orgGUID, userGUID string) (cfclient.Org, error)
	associateOrgAuditorMutex       sync.RWMutex
	associateOrgAuditorArgsForCall []struct {
		orgGUID  string
		userGUID string
	}
	associateOrgAuditorReturns struct {
		result1 cfclient.Org
		result2 error
	}
	associateOrgAuditorReturnsOnCall map[int]struct {
		result1 cfclient.Org
		result2 error
	}
	AssociateOrgManagerStub        func(orgGUID, userGUID string) (cfclient.Org, error)
	associateOrgManagerMutex       sync.RWMutex
	associateOrgManagerArgsForCall []struct {
		orgGUID  string
		userGUID string
	}
	associateOrgManagerReturns struct {
		result1 cfclient.Org
		result2 error
	}
	associateOrgManagerReturnsOnCall map[int]struct {
		result1 cfclient.Org
		result2 error
	}
	GetOrgQuotaByNameStub        func(name string) (cfclient.OrgQuota, error)
	getOrgQuotaByNameMutex       sync.RWMutex
	getOrgQuotaByNameArgsForCall []struct {
		name string
	}
	getOrgQuotaByNameReturns struct {
		result1 cfclient.OrgQuota
		result2 error
	}
	getOrgQuotaByNameReturnsOnCall map[int]struct {
		result1 cfclient.OrgQuota
		result2 error
	}
	ListIsolationSegmentsByQueryStub        func(query url.Values) ([]cfclient.IsolationSegment, error)
	listIsolationSegmentsByQueryMutex       sync.RWMutex
	listIsolationSegmentsByQueryArgsForCall []struct {
		query url.Values
	}
	listIsolationSegmentsByQueryReturns struct {
		result1 []cfclient.IsolationSegment
		result2 error
	}
	listIsolationSegmentsByQueryReturnsOnCall map[int]struct {
		result1 []cfclient.IsolationSegment
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAPI) CreateOrg(req cfclient.OrgRequest) (cfclient.Org, error) {
	fake.createOrgMutex.Lock()
	ret, specificReturn := fake.createOrgReturnsOnCall[len(fake.createOrgArgsForCall)]
	fake.createOrgArgsForCall = append(fake.createOrgArgsForCall, struct {
		req cfclient.OrgRequest
	}{req})
	fake.recordInvocation("CreateOrg", []interface{}{req})
	fake.createOrgMutex.Unlock()
	if fake.CreateOrgStub != nil {
		return fake.CreateOrgStub(req)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.createOrgReturns.result1, fake.createOrgReturns.result2
}

func (fake *FakeAPI) CreateOrgCallCount() int {
	fake.createOrgMutex.RLock()
	defer fake.createOrgMutex.RUnlock()
	return len(fake.createOrgArgsForCall)
}

func (fake *FakeAPI) CreateOrgArgsForCall(i int) cfclient.OrgRequest {
	fake.createOrgMutex.RLock()
	defer fake.createOrgMutex.RUnlock()
	return fake.createOrgArgsForCall[i].req
}

func (fake *FakeAPI) CreateOrgReturns(result1 cfclient.Org, result2 error) {
	fake.CreateOrgStub = nil
	fake.createOrgReturns = struct {
		result1 cfclient.Org
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) CreateOrgReturnsOnCall(i int, result1 cfclient.Org, result2 error) {
	fake.CreateOrgStub = nil
	if fake.createOrgReturnsOnCall == nil {
		fake.createOrgReturnsOnCall = make(map[int]struct {
			result1 cfclient.Org
			result2 error
		})
	}
	fake.createOrgReturnsOnCall[i] = struct {
		result1 cfclient.Org
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) UpdateOrg(orgGUID string, orgRequest cfclient.OrgRequest) (cfclient.Org, error) {
	fake.updateOrgMutex.Lock()
	ret, specificReturn := fake.updateOrgReturnsOnCall[len(fake.updateOrgArgsForCall)]
	fake.updateOrgArgsForCall = append(fake.updateOrgArgsForCall, struct {
		orgGUID    string
		orgRequest cfclient.OrgRequest
	}{orgGUID, orgRequest})
	fake.recordInvocation("UpdateOrg", []interface{}{orgGUID, orgRequest})
	fake.updateOrgMutex.Unlock()
	if fake.UpdateOrgStub != nil {
		return fake.UpdateOrgStub(orgGUID, orgRequest)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.updateOrgReturns.result1, fake.updateOrgReturns.result2
}

func (fake *FakeAPI) UpdateOrgCallCount() int {
	fake.updateOrgMutex.RLock()
	defer fake.updateOrgMutex.RUnlock()
	return len(fake.updateOrgArgsForCall)
}

func (fake *FakeAPI) UpdateOrgArgsForCall(i int) (string, cfclient.OrgRequest) {
	fake.updateOrgMutex.RLock()
	defer fake.updateOrgMutex.RUnlock()
	return fake.updateOrgArgsForCall[i].orgGUID, fake.updateOrgArgsForCall[i].orgRequest
}

func (fake *FakeAPI) UpdateOrgReturns(result1 cfclient.Org, result2 error) {
	fake.UpdateOrgStub = nil
	fake.updateOrgReturns = struct {
		result1 cfclient.Org
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) UpdateOrgReturnsOnCall(i int, result1 cfclient.Org, result2 error) {
	fake.UpdateOrgStub = nil
	if fake.updateOrgReturnsOnCall == nil {
		fake.updateOrgReturnsOnCall = make(map[int]struct {
			result1 cfclient.Org
			result2 error
		})
	}
	fake.updateOrgReturnsOnCall[i] = struct {
		result1 cfclient.Org
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) AddIsolationSegmentToOrg(isolationSegmentGUID string, orgGUID string) error {
	fake.addIsolationSegmentToOrgMutex.Lock()
	ret, specificReturn := fake.addIsolationSegmentToOrgReturnsOnCall[len(fake.addIsolationSegmentToOrgArgsForCall)]
	fake.addIsolationSegmentToOrgArgsForCall = append(fake.addIsolationSegmentToOrgArgsForCall, struct {
		isolationSegmentGUID string
		orgGUID              string
	}{isolationSegmentGUID, orgGUID})
	fake.recordInvocation("AddIsolationSegmentToOrg", []interface{}{isolationSegmentGUID, orgGUID})
	fake.addIsolationSegmentToOrgMutex.Unlock()
	if fake.AddIsolationSegmentToOrgStub != nil {
		return fake.AddIsolationSegmentToOrgStub(isolationSegmentGUID, orgGUID)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.addIsolationSegmentToOrgReturns.result1
}

func (fake *FakeAPI) AddIsolationSegmentToOrgCallCount() int {
	fake.addIsolationSegmentToOrgMutex.RLock()
	defer fake.addIsolationSegmentToOrgMutex.RUnlock()
	return len(fake.addIsolationSegmentToOrgArgsForCall)
}

func (fake *FakeAPI) AddIsolationSegmentToOrgArgsForCall(i int) (string, string) {
	fake.addIsolationSegmentToOrgMutex.RLock()
	defer fake.addIsolationSegmentToOrgMutex.RUnlock()
	return fake.addIsolationSegmentToOrgArgsForCall[i].isolationSegmentGUID, fake.addIsolationSegmentToOrgArgsForCall[i].orgGUID
}

func (fake *FakeAPI) AddIsolationSegmentToOrgReturns(result1 error) {
	fake.AddIsolationSegmentToOrgStub = nil
	fake.addIsolationSegmentToOrgReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAPI) AddIsolationSegmentToOrgReturnsOnCall(i int, result1 error) {
	fake.AddIsolationSegmentToOrgStub = nil
	if fake.addIsolationSegmentToOrgReturnsOnCall == nil {
		fake.addIsolationSegmentToOrgReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addIsolationSegmentToOrgReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAPI) ListOrgsByQuery(query url.Values) ([]cfclient.Org, error) {
	fake.listOrgsByQueryMutex.Lock()
	ret, specificReturn := fake.listOrgsByQueryReturnsOnCall[len(fake.listOrgsByQueryArgsForCall)]
	fake.listOrgsByQueryArgsForCall = append(fake.listOrgsByQueryArgsForCall, struct {
		query url.Values
	}{query})
	fake.recordInvocation("ListOrgsByQuery", []interface{}{query})
	fake.listOrgsByQueryMutex.Unlock()
	if fake.ListOrgsByQueryStub != nil {
		return fake.ListOrgsByQueryStub(query)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.listOrgsByQueryReturns.result1, fake.listOrgsByQueryReturns.result2
}

func (fake *FakeAPI) ListOrgsByQueryCallCount() int {
	fake.listOrgsByQueryMutex.RLock()
	defer fake.listOrgsByQueryMutex.RUnlock()
	return len(fake.listOrgsByQueryArgsForCall)
}

func (fake *FakeAPI) ListOrgsByQueryArgsForCall(i int) url.Values {
	fake.listOrgsByQueryMutex.RLock()
	defer fake.listOrgsByQueryMutex.RUnlock()
	return fake.listOrgsByQueryArgsForCall[i].query
}

func (fake *FakeAPI) ListOrgsByQueryReturns(result1 []cfclient.Org, result2 error) {
	fake.ListOrgsByQueryStub = nil
	fake.listOrgsByQueryReturns = struct {
		result1 []cfclient.Org
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) ListOrgsByQueryReturnsOnCall(i int, result1 []cfclient.Org, result2 error) {
	fake.ListOrgsByQueryStub = nil
	if fake.listOrgsByQueryReturnsOnCall == nil {
		fake.listOrgsByQueryReturnsOnCall = make(map[int]struct {
			result1 []cfclient.Org
			result2 error
		})
	}
	fake.listOrgsByQueryReturnsOnCall[i] = struct {
		result1 []cfclient.Org
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) CreateSpace(req cfclient.SpaceRequest) (cfclient.Space, error) {
	fake.createSpaceMutex.Lock()
	ret, specificReturn := fake.createSpaceReturnsOnCall[len(fake.createSpaceArgsForCall)]
	fake.createSpaceArgsForCall = append(fake.createSpaceArgsForCall, struct {
		req cfclient.SpaceRequest
	}{req})
	fake.recordInvocation("CreateSpace", []interface{}{req})
	fake.createSpaceMutex.Unlock()
	if fake.CreateSpaceStub != nil {
		return fake.CreateSpaceStub(req)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.createSpaceReturns.result1, fake.createSpaceReturns.result2
}

func (fake *FakeAPI) CreateSpaceCallCount() int {
	fake.createSpaceMutex.RLock()
	defer fake.createSpaceMutex.RUnlock()
	return len(fake.createSpaceArgsForCall)
}

func (fake *FakeAPI) CreateSpaceArgsForCall(i int) cfclient.SpaceRequest {
	fake.createSpaceMutex.RLock()
	defer fake.createSpaceMutex.RUnlock()
	return fake.createSpaceArgsForCall[i].req
}

func (fake *FakeAPI) CreateSpaceReturns(result1 cfclient.Space, result2 error) {
	fake.CreateSpaceStub = nil
	fake.createSpaceReturns = struct {
		result1 cfclient.Space
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) CreateSpaceReturnsOnCall(i int, result1 cfclient.Space, result2 error) {
	fake.CreateSpaceStub = nil
	if fake.createSpaceReturnsOnCall == nil {
		fake.createSpaceReturnsOnCall = make(map[int]struct {
			result1 cfclient.Space
			result2 error
		})
	}
	fake.createSpaceReturnsOnCall[i] = struct {
		result1 cfclient.Space
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) AssociateOrgUser(orgGUID string, userGUID string) (cfclient.Org, error) {
	fake.associateOrgUserMutex.Lock()
	ret, specificReturn := fake.associateOrgUserReturnsOnCall[len(fake.associateOrgUserArgsForCall)]
	fake.associateOrgUserArgsForCall = append(fake.associateOrgUserArgsForCall, struct {
		orgGUID  string
		userGUID string
	}{orgGUID, userGUID})
	fake.recordInvocation("AssociateOrgUser", []interface{}{orgGUID, userGUID})
	fake.associateOrgUserMutex.Unlock()
	if fake.AssociateOrgUserStub != nil {
		return fake.AssociateOrgUserStub(orgGUID, userGUID)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.associateOrgUserReturns.result1, fake.associateOrgUserReturns.result2
}

func (fake *FakeAPI) AssociateOrgUserCallCount() int {
	fake.associateOrgUserMutex.RLock()
	defer fake.associateOrgUserMutex.RUnlock()
	return len(fake.associateOrgUserArgsForCall)
}

func (fake *FakeAPI) AssociateOrgUserArgsForCall(i int) (string, string) {
	fake.associateOrgUserMutex.RLock()
	defer fake.associateOrgUserMutex.RUnlock()
	return fake.associateOrgUserArgsForCall[i].orgGUID, fake.associateOrgUserArgsForCall[i].userGUID
}

func (fake *FakeAPI) AssociateOrgUserReturns(result1 cfclient.Org, result2 error) {
	fake.AssociateOrgUserStub = nil
	fake.associateOrgUserReturns = struct {
		result1 cfclient.Org
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) AssociateOrgUserReturnsOnCall(i int, result1 cfclient.Org, result2 error) {
	fake.AssociateOrgUserStub = nil
	if fake.associateOrgUserReturnsOnCall == nil {
		fake.associateOrgUserReturnsOnCall = make(map[int]struct {
			result1 cfclient.Org
			result2 error
		})
	}
	fake.associateOrgUserReturnsOnCall[i] = struct {
		result1 cfclient.Org
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) AssociateOrgAuditor(orgGUID string, userGUID string) (cfclient.Org, error) {
	fake.associateOrgAuditorMutex.Lock()
	ret, specificReturn := fake.associateOrgAuditorReturnsOnCall[len(fake.associateOrgAuditorArgsForCall)]
	fake.associateOrgAuditorArgsForCall = append(fake.associateOrgAuditorArgsForCall, struct {
		orgGUID  string
		userGUID string
	}{orgGUID, userGUID})
	fake.recordInvocation("AssociateOrgAuditor", []interface{}{orgGUID, userGUID})
	fake.associateOrgAuditorMutex.Unlock()
	if fake.AssociateOrgAuditorStub != nil {
		return fake.AssociateOrgAuditorStub(orgGUID, userGUID)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.associateOrgAuditorReturns.result1, fake.associateOrgAuditorReturns.result2
}

func (fake *FakeAPI) AssociateOrgAuditorCallCount() int {
	fake.associateOrgAuditorMutex.RLock()
	defer fake.associateOrgAuditorMutex.RUnlock()
	return len(fake.associateOrgAuditorArgsForCall)
}

func (fake *FakeAPI) AssociateOrgAuditorArgsForCall(i int) (string, string) {
	fake.associateOrgAuditorMutex.RLock()
	defer fake.associateOrgAuditorMutex.RUnlock()
	return fake.associateOrgAuditorArgsForCall[i].orgGUID, fake.associateOrgAuditorArgsForCall[i].userGUID
}

func (fake *FakeAPI) AssociateOrgAuditorReturns(result1 cfclient.Org, result2 error) {
	fake.AssociateOrgAuditorStub = nil
	fake.associateOrgAuditorReturns = struct {
		result1 cfclient.Org
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) AssociateOrgAuditorReturnsOnCall(i int, result1 cfclient.Org, result2 error) {
	fake.AssociateOrgAuditorStub = nil
	if fake.associateOrgAuditorReturnsOnCall == nil {
		fake.associateOrgAuditorReturnsOnCall = make(map[int]struct {
			result1 cfclient.Org
			result2 error
		})
	}
	fake.associateOrgAuditorReturnsOnCall[i] = struct {
		result1 cfclient.Org
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) AssociateOrgManager(orgGUID string, userGUID string) (cfclient.Org, error) {
	fake.associateOrgManagerMutex.Lock()
	ret, specificReturn := fake.associateOrgManagerReturnsOnCall[len(fake.associateOrgManagerArgsForCall)]
	fake.associateOrgManagerArgsForCall = append(fake.associateOrgManagerArgsForCall, struct {
		orgGUID  string
		userGUID string
	}{orgGUID, userGUID})
	fake.recordInvocation("AssociateOrgManager", []interface{}{orgGUID, userGUID})
	fake.associateOrgManagerMutex.Unlock()
	if fake.AssociateOrgManagerStub != nil {
		return fake.AssociateOrgManagerStub(orgGUID, userGUID)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.associateOrgManagerReturns.result1, fake.associateOrgManagerReturns.result2
}

func (fake *FakeAPI) AssociateOrgManagerCallCount() int {
	fake.associateOrgManagerMutex.RLock()
	defer fake.associateOrgManagerMutex.RUnlock()
	return len(fake.associateOrgManagerArgsForCall)
}

func (fake *FakeAPI) AssociateOrgManagerArgsForCall(i int) (string, string) {
	fake.associateOrgManagerMutex.RLock()
	defer fake.associateOrgManagerMutex.RUnlock()
	return fake.associateOrgManagerArgsForCall[i].orgGUID, fake.associateOrgManagerArgsForCall[i].userGUID
}

func (fake *FakeAPI) AssociateOrgManagerReturns(result1 cfclient.Org, result2 error) {
	fake.AssociateOrgManagerStub = nil
	fake.associateOrgManagerReturns = struct {
		result1 cfclient.Org
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) AssociateOrgManagerReturnsOnCall(i int, result1 cfclient.Org, result2 error) {
	fake.AssociateOrgManagerStub = nil
	if fake.associateOrgManagerReturnsOnCall == nil {
		fake.associateOrgManagerReturnsOnCall = make(map[int]struct {
			result1 cfclient.Org
			result2 error
		})
	}
	fake.associateOrgManagerReturnsOnCall[i] = struct {
		result1 cfclient.Org
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) GetOrgQuotaByName(name string) (cfclient.OrgQuota, error) {
	fake.getOrgQuotaByNameMutex.Lock()
	ret, specificReturn := fake.getOrgQuotaByNameReturnsOnCall[len(fake.getOrgQuotaByNameArgsForCall)]
	fake.getOrgQuotaByNameArgsForCall = append(fake.getOrgQuotaByNameArgsForCall, struct {
		name string
	}{name})
	fake.recordInvocation("GetOrgQuotaByName", []interface{}{name})
	fake.getOrgQuotaByNameMutex.Unlock()
	if fake.GetOrgQuotaByNameStub != nil {
		return fake.GetOrgQuotaByNameStub(name)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getOrgQuotaByNameReturns.result1, fake.getOrgQuotaByNameReturns.result2
}

func (fake *FakeAPI) GetOrgQuotaByNameCallCount() int {
	fake.getOrgQuotaByNameMutex.RLock()
	defer fake.getOrgQuotaByNameMutex.RUnlock()
	return len(fake.getOrgQuotaByNameArgsForCall)
}

func (fake *FakeAPI) GetOrgQuotaByNameArgsForCall(i int) string {
	fake.getOrgQuotaByNameMutex.RLock()
	defer fake.getOrgQuotaByNameMutex.RUnlock()
	return fake.getOrgQuotaByNameArgsForCall[i].name
}

func (fake *FakeAPI) GetOrgQuotaByNameReturns(result1 cfclient.OrgQuota, result2 error) {
	fake.GetOrgQuotaByNameStub = nil
	fake.getOrgQuotaByNameReturns = struct {
		result1 cfclient.OrgQuota
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) GetOrgQuotaByNameReturnsOnCall(i int, result1 cfclient.OrgQuota, result2 error) {
	fake.GetOrgQuotaByNameStub = nil
	if fake.getOrgQuotaByNameReturnsOnCall == nil {
		fake.getOrgQuotaByNameReturnsOnCall = make(map[int]struct {
			result1 cfclient.OrgQuota
			result2 error
		})
	}
	fake.getOrgQuotaByNameReturnsOnCall[i] = struct {
		result1 cfclient.OrgQuota
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) ListIsolationSegmentsByQuery(query url.Values) ([]cfclient.IsolationSegment, error) {
	fake.listIsolationSegmentsByQueryMutex.Lock()
	ret, specificReturn := fake.listIsolationSegmentsByQueryReturnsOnCall[len(fake.listIsolationSegmentsByQueryArgsForCall)]
	fake.listIsolationSegmentsByQueryArgsForCall = append(fake.listIsolationSegmentsByQueryArgsForCall, struct {
		query url.Values
	}{query})
	fake.recordInvocation("ListIsolationSegmentsByQuery", []interface{}{query})
	fake.listIsolationSegmentsByQueryMutex.Unlock()
	if fake.ListIsolationSegmentsByQueryStub != nil {
		return fake.ListIsolationSegmentsByQueryStub(query)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.listIsolationSegmentsByQueryReturns.result1, fake.listIsolationSegmentsByQueryReturns.result2
}

func (fake *FakeAPI) ListIsolationSegmentsByQueryCallCount() int {
	fake.listIsolationSegmentsByQueryMutex.RLock()
	defer fake.listIsolationSegmentsByQueryMutex.RUnlock()
	return len(fake.listIsolationSegmentsByQueryArgsForCall)
}

func (fake *FakeAPI) ListIsolationSegmentsByQueryArgsForCall(i int) url.Values {
	fake.listIsolationSegmentsByQueryMutex.RLock()
	defer fake.listIsolationSegmentsByQueryMutex.RUnlock()
	return fake.listIsolationSegmentsByQueryArgsForCall[i].query
}

func (fake *FakeAPI) ListIsolationSegmentsByQueryReturns(result1 []cfclient.IsolationSegment, result2 error) {
	fake.ListIsolationSegmentsByQueryStub = nil
	fake.listIsolationSegmentsByQueryReturns = struct {
		result1 []cfclient.IsolationSegment
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) ListIsolationSegmentsByQueryReturnsOnCall(i int, result1 []cfclient.IsolationSegment, result2 error) {
	fake.ListIsolationSegmentsByQueryStub = nil
	if fake.listIsolationSegmentsByQueryReturnsOnCall == nil {
		fake.listIsolationSegmentsByQueryReturnsOnCall = make(map[int]struct {
			result1 []cfclient.IsolationSegment
			result2 error
		})
	}
	fake.listIsolationSegmentsByQueryReturnsOnCall[i] = struct {
		result1 []cfclient.IsolationSegment
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createOrgMutex.RLock()
	defer fake.createOrgMutex.RUnlock()
	fake.updateOrgMutex.RLock()
	defer fake.updateOrgMutex.RUnlock()
	fake.addIsolationSegmentToOrgMutex.RLock()
	defer fake.addIsolationSegmentToOrgMutex.RUnlock()
	fake.listOrgsByQueryMutex.RLock()
	defer fake.listOrgsByQueryMutex.RUnlock()
	fake.createSpaceMutex.RLock()
	defer fake.createSpaceMutex.RUnlock()
	fake.associateOrgUserMutex.RLock()
	defer fake.associateOrgUserMutex.RUnlock()
	fake.associateOrgAuditorMutex.RLock()
	defer fake.associateOrgAuditorMutex.RUnlock()
	fake.associateOrgManagerMutex.RLock()
	defer fake.associateOrgManagerMutex.RUnlock()
	fake.getOrgQuotaByNameMutex.RLock()
	defer fake.getOrgQuotaByNameMutex.RUnlock()
	fake.listIsolationSegmentsByQueryMutex.RLock()
	defer fake.listIsolationSegmentsByQueryMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeAPI) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cloudfoundry.API = new(FakeAPI)
